# Generated by Django 4.0.3 on 2023-10-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bookingtable'),
    ]

    operations = [
    ]
