# Generated by Django 4.0.3 on 2023-10-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20231002_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='names',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='numbers',
            field=models.IntegerField(null=True),
        ),
    ]
