# Generated by Django 4.0.3 on 2023-11-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_numbers_bookingtable_adult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Everest_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(null=True)),
            ],
        ),
    ]
