# Generated by Django 4.0.3 on 2023-11-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_everest_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Everest_Info',
            new_name='EverestInformation',
        ),
    ]
