# Generated by Django 4.0.3 on 2023-11-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_everest_info_everestinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everestinformation',
            name='data',
            field=models.CharField(max_length=10000),
        ),
    ]
