# Generated by Django 4.0.3 on 2023-12-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_everestinformation_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='everestinformation',
            name='data',
        ),
        migrations.AddField(
            model_name='everestinformation',
            name='para1',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='everestinformation',
            name='para2',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
