# Generated by Django 4.0.3 on 2023-12-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_everestinformation_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EverestItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=10000, null=True)),
                ('details', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
