# Generated by Django 4.0.3 on 2023-12-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_everestitinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Everest_Included_Ornot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.CharField(max_length=10000, null=True)),
                ('excluded', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
