# Generated by Django 4.0.3 on 2023-12-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_everest_included_ornot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200, null=True)),
                ('descr', models.CharField(max_length=2000, null=True)),
                ('topic', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
