# Generated by Django 4.0.3 on 2023-12-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
