# Generated by Django 4.0.3 on 2023-12-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_cards_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
