# Generated by Django 4.0.3 on 2024-01-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_cards_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokhara_Included_Ornot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.CharField(max_length=10000, null=True)),
                ('excluded', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokharaInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.CharField(max_length=10000, null=True)),
                ('para2', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokharaItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=10000, null=True)),
                ('details', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
