# Generated by Django 4.0.3 on 2024-08-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_admin_is_admin_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
