# Generated by Django 4.0.3 on 2024-09-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_productinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('topic', models.CharField(max_length=10000, null=True)),
                ('details', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EverestItinerary',
        ),
    ]
