# Generated by Django 4.0.3 on 2024-10-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_itinerary_delete_everestitinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='product_location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='product_season',
            field=models.TextField(null=True),
        ),
    ]
