# Generated by Django 5.1.2 on 2024-10-18 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_productinfo_product_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('destination_type', models.CharField(choices=[('Beach', 'Beach'), ('City', 'City'), ('Historical', 'Historical'), ('Cultural', 'Cultural'), ('Adventure', 'Adventure')], max_length=50)),
                ('activities', models.TextField()),
                ('seasonality', models.CharField(max_length=50)),
                ('budget_range', models.CharField(choices=[('Budget', 'Budget-Friendly'), ('Mid-range', 'Mid-range'), ('Luxury', 'Luxury')], max_length=50)),
                ('rating', models.FloatField()),
                ('family_friendly', models.BooleanField(default=False)),
                ('eco_friendly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_destination_types', models.CharField(max_length=255)),
                ('preferred_activities', models.CharField(max_length=255)),
                ('preferred_budget_range', models.CharField(choices=[('Budget', 'Budget-Friendly'), ('Mid-range', 'Mid-range'), ('Luxury', 'Luxury')], max_length=50)),
                ('family_friendly', models.BooleanField(default=False)),
                ('eco_friendly', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
