# Generated by Django 5.1.2 on 2024-11-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_destination_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
